#include <QApplication>
#include <QQmlApplicationEngine>

#include <X11/Xlib.h>
#include <X11/keysym.h>
// XTest
#include <X11/extensions/XTest.h>





int main(int argc, char* argv[]) {
    QApplication app(argc, argv);


    QQmlApplicationEngine engine;


    app.installEventFilter(nullptr);

    // Load the QML from the compiled resources. The qrc prefix generated by CMake
    // is "/MouseKeyboardHook/" with the file alias "qml/main.qml", so the correct
    // resource URL is qrc:/MouseKeyboardHook/qml/main.qml
    engine.load(QUrl(QStringLiteral("qrc:/MouseKeyboardHook/qml/main.qml")));

    return QApplication::exec();
}
